### PR TITLE
Add tests for delegations (sign/verify, delegation())

### PR DESCRIPTION
**Pull request by catenocrypt**
- added tests for delegations (sign/verify)
- added tests to Event::delegation()
- fixed a copy-paste error in comparison relation

### CODE REVIEW

**Comment by mikedilger** [comment]
Shit. I thought I could change the parameters of verify_signature since it was new and nobody would have used it yet, right?  Wrong.  I broke your tests.  Can you change the 2 calls to verify_signature() to the new parameters (I swapped the order, made them references, and both are pubkeys (neither is hex)).

**Comment by catenocrypt** [comment]
I've added tests to Event::delegation(), and fixed a copy-paste error in comparison relation.

**Comment by catenocrypt** [comment]
> Can you change the 2 calls to verify_signature() to the new parameters (I swapped the order, made them references, and both are pubkeys (neither is hex)).

Did that, no problem

**Comment by mikedilger** [comment]
Hey! Your tests found a bug! That is what tests are for.
Ready to merge?

**Comment by catenocrypt** [comment]
Ready

**Review by mikedilger — APPROVED** [review]

**Pull request merged**
