### PR TITLE
Log PoW zero bits progress

### PR DESCRIPTION
**Pull request by cryptoquick**
This is helpful for if you have gossip started from CLI, at least. I'm not sure of a good way to stream updates, but that can be added later. For testing, see this branch:

https://github.com/cryptoquick/gossip/tree/PoW-improvements

I then installed it locally with this:

`RUSTFLAGS="-Ctarget-cpu=native --cfg tokio_unstable" cargo install --path .`

Screenshot:

Screenshot from 2023-04-01 08-18-14

### CODE REVIEW

**Comment by cryptoquick** [comment]
It might be cool to have timestamps on this too somehow... But that might need to be added in the client itself.

**Comment by mikedilger** [comment]
Interesting.

println!() isn't appropriate for a library.  We could make new_with_pow() an async function and also pass back a mpsc channel were these messages are written as structs by the threads into the channel.

**Comment by cryptoquick** [comment]
Great point! Though, wouldn't you pass in an mpsc, not return one? Something like tracer can consume messages produced by this method, and others.

**Comment by mikedilger** [comment]
Yeah prob have to pass it in, since async has to return a future.

**Comment by cryptoquick** [comment]
I just added an MPSC sender, does that look good to you? Just know, this would require blocking IO, I'm not sure if you wanted to use tokio's async channel types instead (a whole copy of the entire tokio runtime is not necessary to just have the type).

**Comment by mikedilger** [comment]
std::sync::mpsc::Sender is fine since it will never block.

It should be optional.

**Comment by cryptoquick** [comment]
Okay, I've made the argument optional and renamed it to `msg_sender`, which might be more self-documenting.

**Pull request merged**
